# name: 'run for detect'

# on:
#   workflow_dispatch:
#   schedule:
#     - cron: '0,30 0-14,23 * * *'

# jobs:
#   job1:
#     name: 'Run'
#     runs-on: 'ubuntu-latest'
  
#     steps:
#     - uses: actions/checkout@v2
#     - name: 'Set up Python 3.11'
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.11.1
#     - name: 'Install requests_html'
#       run: |
#         python -m pip install --upgrade pip
#         pip3 install requests_html
#     - name: 'Run main.py'
#       run: 'python ./forserver.py'
#     - name: 'Setup git and Commit'
#       run: |
#         git config --global user.email xxx@xx.com
#         git config --global user.name xxx
#         git add .
#         git commit -m "[Actions]Update" -a
#     - name: 'Push changes'
#       uses: ad-m/github-push-action@master
#       with:
#         github_token: ${{secrets.TOKEN_FOR_GITHUB}}
